version: "3.8"

services: 
  server:
    # image: 'nginx:stable-alpine'
    build: 
      context: .
      # because in nginx.dockerfile , we refer to src & nginx folder . They are outside of the dockerfiles folder . So context should be .
      dockerfile: dockerfiles/nginx.dockerfile
      # and point to the folder contains docker file
    ports: 
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    depends_on: 
      - php
      - mysql  
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    # volumes:
    #   - ./src:/var/www/html:delegated
      # delegated : that means in the container it should write some data there , it's not instantly reflected back to the host machine .
      # instead it's basically processed in batches , perfomance is better
      # it's means the container should not write frequently to /var/www/html folder .
  mysql:
    image:  mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes: 
      - ./src:/var/www/html  
  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php","/var/www/html/artisan"]
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes: 
      - ./src:/var/www/html